# Generated by Django 3.2 on 2022-10-19 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_delete_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientlist',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amount', to='recipes.ingredient', verbose_name='ingredient'),
        ),
        migrations.AlterField(
            model_name='ingredientlist',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amount', to='recipes.recipe', verbose_name='recipe'),
        ),
    ]
