# Generated by Django 3.2 on 2022-10-20 21:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20221020_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientlist',
            name='amount',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='ingredientlist',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amount', to='recipes.ingredient', verbose_name='ingredient'),
        ),
    ]
