# Generated by Django 4.0.6 on 2022-08-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitofmeasurement',
            name='metric',
            field=models.CharField(choices=[('tbsp', 'ст.ложка'), ('tsp', 'ч.л.'), ('quantity', 'штука'), ('percent', 'процент'), ('cup', 'чашка'), ('ounce', 'унция'), ('gram', 'грамм'), ('milliliter', 'мл')], max_length=255, unique=True, verbose_name='metric'),
        ),
    ]
