# Generated by Django 4.0.6 on 2022-08-10 22:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0006_alter_tag_options_alter_tag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='favourite',
            field=models.ManyToManyField(related_name='favourite_recipe', to=settings.AUTH_USER_MODEL, verbose_name='favourite'),
        ),
    ]
