# Generated by Django 3.2 on 2022-10-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_ingredient_measurement_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(help_text='Select image to upload)', upload_to='media/', verbose_name='image'),
        ),
    ]
