# Generated by Django 4.0.6 on 2022-08-11 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_recipe_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='favourite',
        ),
        migrations.AlterField(
            model_name='favouriterecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite', to='recipes.recipe', verbose_name='recipe'),
        ),
    ]
