# Generated by Django 4.0.6 on 2022-08-12 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0008_remove_recipe_favourite_alter_favouriterecipe_recipe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavouriteRecipe',
            new_name='FavoriteRecipe',
        ),
        migrations.AlterField(
            model_name='ingredientlist',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.ingredient', verbose_name='ingredient'),
        ),
    ]
